name: groove
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  audio_video_progress_bar: ^2.0.2
  cloud_firestore: ^4.16.1
  firebase_core: ^2.29.0
  just_audio: ^0.9.37
  image_picker: ^0.8.4+2



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true