// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCYbe3WJPdzVwBDPHWETxBvM1YdCCyTlM',
    appId: '1:824958260846:web:4849f6c56a81a3b817787f',
    messagingSenderId: '824958260846',
    projectId: 'itds283-project',
    authDomain: 'itds283-project.firebaseapp.com',
    storageBucket: 'itds283-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Sp_lzedcbTKm9Md23OV6XSZ3zY2vEy4',
    appId: '1:824958260846:android:da4b8af4efc83f2e17787f',
    messagingSenderId: '824958260846',
    projectId: 'itds283-project',
    storageBucket: 'itds283-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMx29V_ZNiqfSJ8qYoO8GNvhc4E0m00aY',
    appId: '1:824958260846:ios:06a94969730e953917787f',
    messagingSenderId: '824958260846',
    projectId: 'itds283-project',
    storageBucket: 'itds283-project.appspot.com',
    iosBundleId: 'com.example.groove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMx29V_ZNiqfSJ8qYoO8GNvhc4E0m00aY',
    appId: '1:824958260846:ios:06a94969730e953917787f',
    messagingSenderId: '824958260846',
    projectId: 'itds283-project',
    storageBucket: 'itds283-project.appspot.com',
    iosBundleId: 'com.example.groove',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCYbe3WJPdzVwBDPHWETxBvM1YdCCyTlM',
    appId: '1:824958260846:web:afdb1fa9105e4f5917787f',
    messagingSenderId: '824958260846',
    projectId: 'itds283-project',
    authDomain: 'itds283-project.firebaseapp.com',
    storageBucket: 'itds283-project.appspot.com',
  );
}
