// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYaeIfnK1ydWabLa97wjKc3wp96SBh02A',
    appId: '1:309892245616:web:e3bfb4080a10b8847b6cb5',
    messagingSenderId: '309892245616',
    projectId: 'groove-c25e1',
    authDomain: 'groove-c25e1.firebaseapp.com',
    storageBucket: 'groove-c25e1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8UY6VCoDFbQFOc9H1MfTdIoCwmQl6NYQ',
    appId: '1:309892245616:android:dcaa7e27423333477b6cb5',
    messagingSenderId: '309892245616',
    projectId: 'groove-c25e1',
    storageBucket: 'groove-c25e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiYmtOkZbKE4KrbE590rzic_nNaFZnm7w',
    appId: '1:309892245616:ios:9b6319ed2b7c9e827b6cb5',
    messagingSenderId: '309892245616',
    projectId: 'groove-c25e1',
    storageBucket: 'groove-c25e1.appspot.com',
    iosBundleId: 'com.example.groove',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiYmtOkZbKE4KrbE590rzic_nNaFZnm7w',
    appId: '1:309892245616:ios:9b6319ed2b7c9e827b6cb5',
    messagingSenderId: '309892245616',
    projectId: 'groove-c25e1',
    storageBucket: 'groove-c25e1.appspot.com',
    iosBundleId: 'com.example.groove',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYaeIfnK1ydWabLa97wjKc3wp96SBh02A',
    appId: '1:309892245616:web:298587251882a4ea7b6cb5',
    messagingSenderId: '309892245616',
    projectId: 'groove-c25e1',
    authDomain: 'groove-c25e1.firebaseapp.com',
    storageBucket: 'groove-c25e1.appspot.com',
  );

}